import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { templates } from "@/lib/templates";
import { SectionRenderer } from "@/lib/registry";
import { themeToCSSVars } from "@/lib/theme/tokens";

export default function HomePage() {
  const t = templates[0];
  return <main style={themeToCSSVars(t.theme) as React.CSSProperties} className="min-h-screen bg-[var(--bg-base)] text-white"><Navbar /><section className="relative grid min-h-[calc(100svh-64px)] place-items-center overflow-hidden px-4 py-20 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,var(--glow-primary),transparent_32%),radial-gradient(circle_at_80%_15%,var(--glow-secondary),transparent_34%),linear-gradient(180deg,#030712,var(--bg-base))]" /><div className="premium-grid absolute inset-0 opacity-80" /><div className="noise-layer absolute inset-0 opacity-[.04]" /><div className="relative z-10 mx-auto max-w-5xl"><p className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-sm font-medium text-white/70 backdrop-blur-md"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_18px_rgba(103,232,249,.9)]" />Premium SaaS для малого бизнеса</p><h1 className="text-4xl font-black leading-[.95] tracking-[-.04em] sm:text-5xl md:text-7xl lg:text-8xl">Готовый сайт за 3 дня <span className="gradient-text">без предоплат</span> — от <span className="whitespace-nowrap">9 900 ₽</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-white/70 md:text-2xl">Кофейни, рестораны, салоны красоты, автомойки и клининг. Вы выбираете шаблон — мы делаем техническое.</p><div className="mt-10 flex flex-col justify-center gap-3 xs:flex-row"><Link className="primary-cta shimmer rounded-full px-7 py-4 font-black text-black" href="/templates">Выбрать шаблон</Link><Link className="secondary-cta rounded-full px-7 py-4 font-bold text-white" href="/customize/coffee-shop">Открыть демо</Link></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce text-white/40">⌄</div></section><SectionRenderer template={t} /></main>;
}
