import type { Section, Template } from "@/types";
import { getCardClass, getHeadingClass, getRadiusClass, getSectionPadding, themeToCSSVars } from "@/lib/theme/tokens";
function money(v: unknown){return Number(v).toLocaleString("ru-RU")}
type Props={section:Section; template:Template};
const Wrap=({children,template}:{children:React.ReactNode;template:Template})=><section className={`${getSectionPadding(template.style)} px-4 sm:px-6`}><div className="mx-auto max-w-6xl">{children}</div></section>;
function Hero({section,template}:Props){const c=section.content; const centered=c.layout==="centered"||template.style.heroTextAlign==="center"; return <Wrap template={template}><div className={`grid gap-8 ${centered?"text-center place-items-center":"md:grid-cols-2 items-center"}`}><div><p className="mb-4 inline-flex rounded-full border border-[var(--bg-border)] px-4 py-2 text-sm text-[var(--text-secondary)]">{String(c.badge??"")}</p><h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black tracking-tight">{String(c.headline??"")}</h1><p className="mt-5 max-w-2xl text-base sm:text-lg text-[var(--text-secondary)]">{String(c.subheadline??"")}</p><div className="mt-7 flex flex-col xs:flex-row gap-3"><a className="rounded-full bg-[var(--primary)] px-5 sm:px-7 py-3 text-sm sm:text-[15px] font-bold text-black" href="#lead">{String(c.cta??"Заказать")}</a><a className="rounded-full border border-[var(--bg-border)] px-5 sm:px-7 py-3 text-sm sm:text-[15px]" href="#services">{String(c.secondaryCta??"Подробнее")}</a></div></div><div className={`${getCardClass(template.style)} min-h-64 w-full p-5`}><div className="h-56 rounded-[inherit] bg-gradient-to-br from-[var(--gradient-from)] to-[var(--gradient-to)] opacity-80" /></div></div></Wrap>}
function Stats({section,template}:Props){const items=(section.content.items as any[])??[]; return <Wrap template={template}><div className={template.style.statsLayout==="inline"?"flex flex-wrap gap-4":"grid grid-cols-1 sm:grid-cols-3 gap-4"}>{items.map((it,i)=><div key={i} className={`${getCardClass(template.style)} p-5 text-center`}><div className="text-2xl sm:text-3xl font-black"><span className="whitespace-nowrap">{it.prefix}{it.value==="9900"?money(it.value):it.value}{it.suffix}</span></div><p className="text-sm text-[var(--text-muted)]">{it.label}</p></div>)}</div></Wrap>}
function About({section,template}:Props){return <Wrap template={template}><div className={`${getCardClass(template.style)} p-6 sm:p-8`}><h2 className={getHeadingClass(template.style)}>{String(section.content.title??"")}</h2><p className="mt-4 text-[var(--text-secondary)]">{String(section.content.text??"")}</p></div></Wrap>}
function Gallery({section,template}:Props){const items=(section.content.images as string[])??[]; const film=template.style.galleryStyle==="film"; const isUrl=(s:string)=>/^https?:\/\/|^\//.test(s); return <Wrap template={template}><div className={film?"flex gap-4 overflow-x-auto pb-4":"grid grid-cols-2 gap-4"}>{items.map((x,i)=><div key={i} className={`${getRadiusClass(template.style)} ${film?"w-[min(280px,72vw)] shrink-0":""} relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-[var(--primary)]/40 to-[var(--secondary)]/20`}>{isUrl(x)?<img src={x} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<span className="absolute bottom-4 left-4 text-sm">{x}</span>}</div>)}</div></Wrap>}
function Services({section,template}:Props){const items=(section.content.items as string[])??[]; return <Wrap template={template}><h2 id="services" className={getHeadingClass(template.style)}>{String(section.content.title??"Услуги")}</h2><div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">{items.map(x=><div key={x} className={`${getCardClass(template.style)} p-5`}>{x}</div>)}</div></Wrap>}
function Simple({section,template}:Props){return <Wrap template={template}><div className={`${getCardClass(template.style)} p-6`}><h2 className={getHeadingClass(template.style)}>{String(section.content.title??section.type)}</h2><p className="mt-3 text-[var(--text-secondary)]">{String(section.content.text??"Оставьте заявку — подготовим сайт под ваш бизнес.")}</p></div></Wrap>}
function Reviews({section,template}:Props){const items=(section.content.items as string[])??[]; return <Wrap template={template}><h2 className={getHeadingClass(template.style)}>{String(section.content.title??"Отзывы")}</h2><div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">{items.map(x=><blockquote key={x} className={`${getCardClass(template.style)} p-5`}>“{x}”</blockquote>)}</div></Wrap>}
export const SectionRegistry={hero:Hero,stats:Stats,about:About,gallery:Gallery,services:Services,"hosting-service":Simple,"templates-gallery":Simple,calculator:Simple,footer:Simple,reviews:Reviews};
export function SectionRenderer({template}:{template:Template}){return <div style={themeToCSSVars(template.theme) as React.CSSProperties} className="min-h-screen bg-[var(--bg-base)] text-[var(--text-primary)]">{template.sections.map(section=>{const C=SectionRegistry[section.type]; return <C key={section.id} section={section} template={template}/>})}</div>}
